import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@coinbase/onchainkit/styles.css';
import OnchainProviders from "./OnchainProviders";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OCK Wallet Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OnchainProviders>
          {children}
        </OnchainProviders>
        </body>
    </html>
  );
}
